server:
  port: 20100

spring:
  application.name: sojson.sso.registry
  security:
    user:
      name: admin
      password: 123456

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    #没这句，报org.apache.http.conn.ConnectTimeoutException: Connect to localhost:8761 timed out
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:${server.port}/eureka/
